### ISSUE TITLE
关于XML编译

### ISSUE THREAD

**Issue by chriscp-cat** [vczh-libraries/Release#14]
官方的例子似乎没有自动编译  我暂时是这么写的 
但是没法在编译失败时查看报错和停止
后面会考虑添加这方面的东西吗
![image](https://user-images.githubusercontent.com/68489543/193404726-2439791c-d2bf-48a4-85c2-bd2a24a25172.png)

**Comment by vczh** [comment]
我自己都是在powershell里面调用的，判断错误的方法是看看有没有输出错误信息到文件里面。
