### ISSUE TITLE
GacUI.h里StrongTypedColumnProvider类的GetCellDataRext成员

### ISSUE THREAD

**Issue by Phuehvk** [vczh-libraries/Release#2]
此函数调用description::BoxValue，返回vl::reflection.::description::Value对象，但Value雷里没GetText成员，此前的版本里有，貌似被改成了GetBoxValue

**Comment by vczh** [comment]
1. 拿到Value.GetTypeDescriptor()->GetSerializableType()，看看是不是null
2. 如果是nullptr，那么哪怕它是BoxedValue你也拿不到字符串
3. 如果不是nullptr，就调用它的Serialize函数

现在struct和enum都不是serializable的，不过你可以从ITypeDescriptor里面拿到所有元数据，输出自己想要的格式。刚发的Release鼓励你不使用反射，所以如果你确实知道他是什么，那么你就Unbox出来自己整好了。对于primitive type，你可以用TypedValueSerializerProvider<T>来获得字符串。这仍然不包括struct和enum。
