### ISSUE TITLE
The release version number and the release version package version number are inconsistent

### ISSUE THREAD

**Issue by jimwang118** [vczh-libraries/Release#20]
The release version number is 1.2.10.1, and the compressed package version number of the release version is 1.12.10.1.

**Comment by pzhlkj6612** [comment]
The previous tag is [1.2.10.0](https://github.com/vczh-libraries/Release/tree/1.2.10.0), so I think the [1.12.10.1](https://github.com/vczh-libraries/Release/tree/1.12.10.1) tag is a typo.

**Comment by jimwang118** [comment]
> The previous tag is [1.2.10.0](https://github.com/vczh-libraries/Release/tree/1.2.10.0), so I think the [1.12.10.1](https://github.com/vczh-libraries/Release/tree/1.12.10.1) tag is a typo.

Yes, so the release zip file should be modified to 1.2.10.1.

**Comment by jimwang118** [comment]
@vczh Please fix the version number of the released compressed package to the correct version 1.2.10.1.

**Comment by pzhlkj6612** [comment]
> Yes, so the release zip file should be modified to 1.2.10.1.

Well, the filename of those "source code" assets are the same as the tag name, so vczh can't directly rename them, but recreate a new tag.
