### ISSUE TITLE
Command line help

### ISSUE THREAD

**Issue by gvanem** [vczh-libraries/Release#3]
This is one of the most confusing projects I've seen in a long time.
At least add a `GacGen32.exe [-h | --help]` option to briefly tell what it can do. Instead with a
`GacGen32.exe --help`, it produces this junk:
```
--help.log\x32\Errors.txt
--help.log\x64\Errors.txt
```
in current directory.

But I was barely able to `msbuild ` some of the `*.vcxproj` files and ran some examples. Pretty cool stuff!

**Comment by vczh** [comment]
What you need is `GacBuild.ps1`. You are not expected to run `GacGen32.exe` or `GacGen64.exe` by yourself.
