### ISSUE TITLE
11

### ISSUE THREAD

**Issue by showmelyn** [vczh-libraries/Release#4]
https://github.com/vczh-libraries/Release/blob/2318b15b3e5c6c7febe7338e4b31651545ad472c/Import/GacUI.h#L69

**Comment by vczh** [comment]
The comment is kind of simple, it means when you choose UpLeft, objects go from the bottom-right corner towards up, and when a column is fully filled, it moves 1 step to left, and goes from bottom to up again. So UpLeft means going up first and then left. It is similar to LeftUp, which means going left first instead.

It will be more clear when the Document repo is finished, and then I use it to write more accurate documents.
