### ISSUE TITLE
如何创建基于GacLib 的 VS 工程？

### ISSUE THREAD

**Issue by krurkshell** [vczh-libraries/Release#5]
轮子哥， 我看了你的 tutorial， 创建了对应的文件夹和文件， 也成功运行了 GacBuild.ps1， 可是怎么能在 vs 里面运行项目呢？没有对应的 sln 文件或者 vcxproj 文件啊，希望你的 tutorial 能做一个小白教程， 就是怎么从0 开始创建一个基于GacLib 的项目， 然后运行成功的实例 或者 给一个 props 模板， GacBuild.ps1 运行完了， 通过 属性管理器添加 props 文件后 ， 就可以buidl and run 的那种。

**Comment by pzhlkj6612** [comment]
Hi. `./Tutorial/GacUI_*`文件夹下的那个`.sln`解决方案你打开过了吗？

**Comment by krurkshell** [comment]
> Hi. `./Tutorial/GacUI_*`文件夹下的那个`.sln`解决方案你打开过了吗？

打开过了， 并且都运行成功了。

**Comment by krurkshell** [comment]
经过自己摸索了一下， 终于跑起来了， 哈哈哈！

**Comment by vczh** [comment]
@krurkshell  http://www.gaclib.net/tutorial.html

**Comment by krurkshell** [comment]
> @krurkshell http://www.gaclib.net/tutorial.html

我已经读过了轮子哥的 tutorial, 开始我对vs 不熟，按照tutorial 操作完后 ， 不知道怎么转为 vs 项目， 现在摸索了一下，可以跑起来了。

**Comment by vczh** [comment]
@krurkshell 

“转为vs项目”这个描述很奇怪，你只要把GacUI、生成的和你写的C++文件全部拖进项目里就好了。

**Comment by krurkshell** [comment]
感谢轮子的哥的回复， 我现在已经可以成功运行起来了。
