### ISSUE TITLE
能创建一个支持libcef网页的Demo吗?

### ISSUE THREAD

**Issue by jubeiot** [vczh-libraries/Release#8]
不知道如何下手, 作者懂原理,可以给我小白普及一下

**Comment by vczh** [comment]
没用过。chromium是支持directwrite的，我猜他也能用direct2d渲染，这个肯定有人干过。你放一个Direct2DElement（参考时钟tutorial），然后永提供给你的设备对象搭配使用即可。

**Comment by vczh** [comment]
现已开通Discussion，欢迎使用
